export const DATABASE_MIGRATION_PORT = Symbol("DATABASE_MIGRATION_PORT");
export const BIRTHDAY_MESSAGE_GENERATOR = Symbol("BIRTHDAY_MESSAGE_GENERATOR");
export const RUN_BIRTHDAY_REMINDER_USE_CASE = Symbol("RUN_BIRTHDAY_REMINDER_USE_CASE");
export const WHATSAPP_CLIENT = Symbol("WHATSAPP_CLIENT");
