export { DATABASE_MIGRATION_PORT, TARGET_CONFIGURATION_PORT } from "../tokens.js";

export const BIRTHDAY_AUTOMATION_WORKFLOW = Symbol("BIRTHDAY_AUTOMATION_WORKFLOW");
export const AUTOMATION_WORKFLOW_REGISTRATION = Symbol("AUTOMATION_WORKFLOW_REGISTRATION");
